name: env_temporal_ml
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib-base=3.9.2
  - pip=25.0
  - pycodestyle=2.12.1
  - pyparsing=3.2.0
  - python=3.9.18
  - readline=8.2
  - seaborn=0.13.2
  - unicodedata2=15.1.0
  - pip:
      - geomloss==0.2.6
      - mpmath==1.3.0
      - numpy==1.25.2
      - opendataval==1.3.0
      - pandas==1.5.3
      - pyyaml==6.0.2
      - scikit-learn==1.3.0
      - scipy==1.13.1
      - shap==0.42.1
      - xgboost==1.7.5
